Moviecatalog/Controllers/MoviesController.cs
using Microsoft.AspNet.Identity;
using Moviecatalog.Models;
using Moviecatalog.Models.Identity;
using Moviecatalog.Repositories;
using Moviecatalog.ViewModels;
using Moviecatalog.ViewModels.MovieViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Moviecatalog.Controllers
{
    public class MoviesController : Controller
    {
        private MovieRepository movieRepository = new MovieRepository();
        private ApplicationUserRepository userRepository = new ApplicationUserRepository();
        private int pageSize = 5;

        public ActionResult Index(int page = 1)
        {
            if (Request == null || Request.HttpMethod == "GET")
            {
                string sort = "1";
                if (TempData["sort"] != null)
                    sort = TempData["sort"].ToString();

                IEnumerable<Movies> movies;
                switch (sort)
                {
                    case "2":
                        movies = movieRepository.GetPage(movieRepository.GetAll().OrderByDescending(movie => movie.title), pageSize, page);
                        break;
                    case "3":
                        movies = movieRepository.GetPage(movieRepository.GetAll().OrderBy(movie => movie.yearRelease), pageSize, page);
                        break;
                    case "4":
                        movies = movieRepository.GetPage(movieRepository.GetAll().OrderByDescending(movie => movie.yearRelease), pageSize, page);
                        break;
                    default:
                        movies = movieRepository.GetPage(movieRepository.GetAll().OrderBy(movie => movie.title), pageSize, page);
                        break;
                }

                IEnumerable<ApplicationUser> users = userRepository.GetAll();

                IEnumerable<MoviesView> moviesView = from movie in movies
                                                     join user in users on movie.userPosted equals user.Id
                                                     select new MoviesView
                                                     {
                                                         Id = movie.Id,
                                                         title = movie.title,
                                                         description = movie.description,
                                                         yearRelease = movie.yearRelease,
                                                         director = movie.director,
                                                         userPosted = movie.userPosted,
                                                         poster = movie.poster,
                                                         Nick = user.Nick
                                                     };

                int itemsTotal = movieRepository.GetAll().Count();
                int pagesTotal = (int)Math.Ceiling((decimal)(itemsTotal / pageSize)) + (itemsTotal % pageSize > 0 ? 1 : 0);
                MoviesViewModel moviesViewModel = new MoviesViewModel()
                {
                    pageInfo = new PageInfo(pageSize, pagesTotal),
                    moviesView = moviesView,
                };
                moviesViewModel.pageInfo.SetCurrentPageNumber(page);

                ViewBag.sort = sort;
                return View(moviesViewModel);
            }

            else if (Request.HttpMethod == "POST")
            {
                page = (page < 1 ? 1 : page);
                string sort = (Request.Form["sort"]);
                TempData["sort"] = sort;
                return RedirectToAction(null, null, new { page = page });
            }
            return View();
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movies movies = movieRepository.Get(id);
            if (movies == null)
            {
                return HttpNotFound();
            }
            return View(movies);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,title,description,yearRelease,director,userPosted,poster")] Movies movies, HttpPostedFileBase uploadImage)
        {

            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                    }
                    movies.poster = imageData;
                }
                movies.userPosted = User.Identity.GetUserId().ToString();
                movies.Id = Guid.NewGuid();
                movieRepository.Create(movies);
                return RedirectToAction("Index");
            }

            return View(movies);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movies movies = movieRepository.Get(id);
            if (movies == null)
            {
                return HttpNotFound();
            }
            return View(movies);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,title,description,yearRelease,director,userPosted,poster")] Movies movies, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                    }
                    movies.poster = imageData;
                }
                else
                {
                    movies.poster = movieRepository.Get(movies.Id).poster;
                }
                movies.userPosted = User.Identity.GetUserId().ToString();
                movieRepository.Update(movies);
                return RedirectToAction("Index");
            }
            return View(movies);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movies movies = movieRepository.Get(id);
            if (movies == null)
            {
                return HttpNotFound();
            }
            return View(movies);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            movieRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public ActionResult About()
        {
            ViewBag.Message = "Решение тестовго задания на вакансию Asp.Net-разработчик.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "E-mail: andry122003@list.ru";

            return View();
        }

        public ActionResult GetPoster(Guid? id)
        {
            Movies movie = movieRepository.Get(id);
            if (movie.poster != null)
                return File(movie.poster, "image/gif");
            else
                return File(new byte[] { }, "image/gif");
        }
    }
}

Moviecatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @DateTime.Now.Year </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        function LoadingHide()
        {
            $("#loadingGif").css("display", "none");
        }
        function LoadingShow() {
            $("#loadingGif").css("display", "");
        }
    </script>
</head>
<body>
@Html.Partial("~/Views/Shared/_LoadingWait.cshtml")
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="~//Pictures/movie.png" alt="Movie Catalog" style="height: 125%;"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Домашняя страница", "Index", "Movies")</li>
                <li>@Html.ActionLink("Информация", "About", "Movies")</li>
                <li>@Html.ActionLink("Связаться", "Contact", "Movies")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - каталог фильмов (ASP.NET)</p>
    </footer>
</div>

@RenderSection("scripts", required: false)
</body>
</html>

Moviecatalog/Views/Shared/_LoadingWait.cshtml
<div id="loadingGif" style="top: 50%; left: 50%; width: 50px; height: 50px; position: fixed; margin-top: -25px;	margin-left: -25px; padding:0px; z-index:99999999; display:none;">
    <img src="~/Pictures/loading.gif" />
</div>